### PR TITLE
Operation unit tests

### PR DESCRIPTION
**Pull request by maleck13**
Adding some basic unit tests for some of the operations. 
Also small refactors to help with the tests and lint.
The idea here is to show developers how they can approach testing their broker, particularly around the use of the client and fakes (something I was unaware of before this).

@bparees Interested in your thoughts on this, if you feel it is a good idea to add these kinds of tests, I will fill out the rest of the operations

### CODE REVIEW

**Comment by bparees** [comment]
it looks reasonable to me.  wdyt @jim-minter and @pmorie ?

**Comment by maleck13** [comment]
Added tests for each operation now plus a few minor changes to the implementations. The idea here is to show developers how they can approach testing their broker, particularly around the use of the client and fakes.
Each test is a separate commit at the moment, but happy to squash down.

**Comment by jim-minter** [comment]
lgtm - many thanks.  @maleck13, one non-blocking comment that I expect you might disagree with, having seen http://idiomaticgo.com/post/testing/idiomatic-go-tests/ :smiley: : throughout the openshift codebase by convention we don't put _test.go files in a separate package, so that non-exported stuff can be accessed where needed.  I'd personally rather stick to that style here; if not I can see it potentially being changed as a follow-up one day.

**Comment by maleck13** [comment]
@jim-minter thanks for the review. Don't think I have had one of my blogposts referenced in a PR before :) . Made me smile thanks for that. While I would generally use the separate package approach for tests, I see no problem with the change you are requesting. I will make the change and push it up.

**Comment by bparees** [comment]
can you add an invocation of this to the .travis.yml?

**Comment by bparees** [comment]
as for squashing, you can squash or i'll squash on merge.

**Comment by maleck13** [comment]
Added call to make test as requested

**Comment by bparees** [comment]
thanks @maleck13!

**Pull request merged**
